services:
  postgres:
    image: postgres:15
    container_name: postgres_planner
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespw
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
